[versions]
kotlin = "1.9.10"
composeBom = "2023.10.01"
lifecycle = "2.6.2"
navigation = "2.7.5"
koin = "3.5.0"
datastore = "1.0.0"
junit = "4.13.2"
coroutines = "1.7.3"
compileSdk = "34"
minSdk = "26"
targetSdk = "34"
composeCompiler = "1.5.3"
activityCompose = "1.8.2"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
junit = { module = "junit:junit", version.ref = "junit" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[bundles]
compose = ["compose-ui", "compose-ui-preview", "compose-material3"]

[plugins]
android-application = { id = "com.android.application", version = "8.2.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
